FROM public.ecr.aws/lambda/python:3.10

# Copy function code and models into our /var/task
COPY ./ ${LAMBDA_TASK_ROOT}/

RUN pip install --upgrade pip

# Install system dependencies required for Rust
RUN yum install -y curl gcc && \
    yum clean all

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
ENV PATH="/root/.cargo/bin:${PATH}"

# Verify installation
RUN rustc --version && \
    cargo --version

# install our dependencies
RUN python3 -m pip install -r requirements.txt --target ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "handler.classify" ]